# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  minor: 0

# ##veracode connection Name
#   veracode: 'Veracode'
#   veracodeAppProfile: 'CDT.beta.template.webtools.website'

# ##sonarqube connection name and project name
#   SonarQubeConnection: 'sonar'
#   SonarQubeProjectName: 'CDT.beta.template.webtools.website'

name: $(major).$(minor)$(Rev:.r)
  
steps:
- script: |
    echo '##vso[task.setvariable variable=REACT_APP_VERSION]$(Build.BuildNumber)'
  displayName: set environment variable for subsequent steps
  
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# - task: SonarQubePrepare@5
#   displayName: 'SonarQube Prepare Analysis Configuration'
#   inputs:
#     SonarQube: '$(SonarQubeConnection)'
#     scannerMode: 'CLI'
#     configMode: 'manual'
#     cliProjectKey: '$(SonarQubeProjectName)'
#     cliProjectName: '$(SonarQubeProjectName)'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: "npm install"

- script: npm run test
  displayName: "npm test"
  env:
    CI: true

# - task: PublishCodeCoverageResults@1
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: 'coverage/cobertura-coverage.xml'
#     reportDirectory: 'coverage'
#   displayName: 'Publish Code Coverage'
    
- script: npm run build
  displayName: "npm build"

- task: CopyFiles@2
  inputs:
    Contents: '_site/**' # Pull the build directory
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/_site' # build files
    ArtifactName: 'drop' # output artifact named drop

- task: ArchiveFiles@2
  displayName: 'Archive Build Folder'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/_site'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip' 
    includeRootFolder: false

# - task: Veracode@3
#   displayName: 'Veracode upload and scan: $(build.artifactstagingdirectory)'
#   inputs:
#     ConnectionDetailsSelection: 'Endpoint'
#     AnalysisService: '$(veracode)'
#     veracodeAppProfile: '$(veracodeAppProfile)'
#     version: '$(build.buildNumber)'
#     filepath: '$(build.artifactstagingdirectory)/app.zip'
#     createProfile: true
#     maximumWaitTime: '360'
#   continueOnError: true

# - task: SonarQubeAnalyze@5
#   displayName: Run code quality analysis

# - task: SonarQubePublish@5
#   displayName: Publish code quality analysis
#   inputs:
#     pollingTimeoutSec: '300'
